import type { Metadata } from "next";

import { StoreSvg } from "@/app/layout-svg";
import { Footer } from "@/ui/footer/Footer";
import { Navbar } from "@/ui/navbar/Navbar";

// route specific css
import "./catalog.css";
import "./css/icon.css";
import "./store.css";
import "./styles/style1.css";
import "./styles/style2.css";
import "./styles/style3.css";
import "./styles/style4.css";
import "./styles/style5.css";
import "./styles/style6.css";
import "./styles/style7.css";
import "./styles/style8.css";
import "./styles/style9.css";
// default css
import "../../../assets/css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  params: any;
  children: React.ReactNode;
}) {
  return (
    <>
      {/* <!-- force end any comment tags before the partial --> */}
      <div ng-app="menuCompanion" className="ng-scope">
        <StoreSvg />
        <Navbar />
        {children}
        <Footer />
      </div>
    </>
  );
}
